name: CI-Pipeline

on:
  workflow_call:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: setup environment
        uses: tzuyi0817/coding-standards/.github/actions/setup-environment@main

      - name: install Playwright browsers
        run: npx playwright install --with-deps

      - name: run e2e test
        run: pnpm test:ci-e2e
