name: Deploy to Production

on:
  push:
    branches: [main]
    paths:
      - index.html
      - 'src/**'
      - pnpm-lock.yaml
      - package.json

jobs:
  e2e-test:
    uses: tzuyi0817/workflows/.github/workflows/test.yml@v1
    with:
      install-other-deps: pnpm dlx playwright install --with-deps
      test: pnpm test:ci-e2e

  deploy:
    needs: e2e-test
    uses: tzuyi0817/workflows/.github/workflows/deploy-vercel.yml@v1
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}

    with:
      environment: Production
      prod: true
