name: Deploy to Production

env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'pnpm-lock.yaml'
      - 'package.json'

jobs:
  CI:
    uses: './.github/workflows/ci.yml'

  deploy:
    needs: CI
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v5
      - name: install pnpm
        uses: pnpm/action-setup@v3

      - name: install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: deploy project artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
